package GUI;

import Classes.Score;
import DAO.ScoreDAO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

public class AlteraScore2 extends javax.swing.JFrame {
    private ScoreDAO scoreDAO;
    private ArrayList<Score> scores;
    
    public AlteraScore2() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null); // Centralizar na tela
        
        scoreDAO = new ScoreDAO();
        carregarScores();
        
        // Desabilitar edição inicialmente
        toggleCamposEdicao(false);
    }
    
    private void carregarScores() {
        scores = scoreDAO.listarTodos();
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        
        for (Score s : scores) {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            String dataFormatada = sdf.format(s.getData());
            model.addElement("ID: " + s.getId_score() + " | Score: " + s.getScore() + " | Data: " + dataFormatada);
        }
        
        jComboBoxScores.setModel(model);
        
        if (scores.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nenhum score cadastrado para alteração.");
            dispose();
        }
    }
    
    private void toggleCamposEdicao(boolean habilitar) {
        jTextFieldNovoScore.setEnabled(habilitar);
        jFormattedTextFieldNovaData.setEnabled(habilitar);
        jButtonConfirmar.setEnabled(habilitar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelSelecionar = new javax.swing.JLabel();
        jComboBoxScores = new javax.swing.JComboBox<>();
        jLabelNovoScore = new javax.swing.JLabel();
        jTextFieldNovoScore = new javax.swing.JTextField();
        jLabelNovaData = new javax.swing.JLabel();
        jFormattedTextFieldNovaData = new javax.swing.JFormattedTextField();
        jButtonCarregar = new javax.swing.JButton();
        jButtonConfirmar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alteração de Score");

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTitulo.setText("Alteração de Score");

        jLabelSelecionar.setText("Selecione o score para alterar:");

        jLabelNovoScore.setText("Novo Score:");

        jTextFieldNovoScore.setEnabled(false);

        jLabelNovaData.setText("Nova Data:");

        try {
            jFormattedTextFieldNovaData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldNovaData.setEnabled(false);

        jButtonCarregar.setText("Carregar Dados");
        jButtonCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarregarActionPerformed(evt);
            }
        });

        jButtonConfirmar.setText("Confirmar Alteração");
        jButtonConfirmar.setEnabled(false);
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitulo)
                    .addComponent(jLabelSelecionar)
                    .addComponent(jComboBoxScores, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelNovoScore)
                            .addComponent(jTextFieldNovoScore)
                            .addComponent(jLabelNovaData)
                            .addComponent(jFormattedTextFieldNovaData, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCarregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addGap(18, 18, 18)
                .addComponent(jLabelSelecionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxScores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNovoScore)
                    .addComponent(jButtonCarregar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNovoScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConfirmar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNovaData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldNovaData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jButtonCarregarActionPerformed(java.awt.event.ActionEvent evt) {                                                
        int selectedIndex = jComboBoxScores.getSelectedIndex();
        if (selectedIndex >= 0 && selectedIndex < scores.size()) {
            Score scoreSelecionado = scores.get(selectedIndex);
            
            jTextFieldNovoScore.setText(String.valueOf(scoreSelecionado.getScore()));
            
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            jFormattedTextFieldNovaData.setText(sdf.format(scoreSelecionado.getData()));
            
            toggleCamposEdicao(true);
        }
    }                                               

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        int selectedIndex = jComboBoxScores.getSelectedIndex();
        if (selectedIndex < 0 || selectedIndex >= scores.size()) {
            JOptionPane.showMessageDialog(this, "Selecione um score válido.");
            return;
        }
        
        Score scoreSelecionado = scores.get(selectedIndex);
        
        // Validar novo score
        String novoScoreStr = jTextFieldNovoScore.getText().trim();
        if (novoScoreStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe o novo score.");
            jTextFieldNovoScore.requestFocus();
            return;
        }
        
        int novoScore;
        try {
            novoScore = Integer.parseInt(novoScoreStr);
            if (novoScore < 0) {
                JOptionPane.showMessageDialog(this, "O score deve ser um valor positivo.");
                jTextFieldNovoScore.requestFocus();
                return;
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Score inválido. Informe um número inteiro.");
            jTextFieldNovoScore.requestFocus();
            return;
        }
        
        // Validar nova data
        String novaDataStr = jFormattedTextFieldNovaData.getText().trim();
        if (novaDataStr.replace("_", "").replace("/", "").length() != 8) {
            JOptionPane.showMessageDialog(this, "Data inválida. Utilize o formato dd/MM/yyyy.");
            jFormattedTextFieldNovaData.requestFocus();
            return;
        }
        
        java.util.Date novaData;
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            sdf.setLenient(false); // Não permitir datas inválidas como 31/02/2023
            novaData = sdf.parse(novaDataStr);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Data inválida. Verifique o formato dd/MM/yyyy.");
            jFormattedTextFieldNovaData.requestFocus();
            return;
        }
        
        // Confirmar alteração
        int confirm = JOptionPane.showConfirmDialog(this, 
                "Confirma a alteração do score?\nID: " + scoreSelecionado.getId_score() +
                "\nNovo Score: " + novoScore +
                "\nNova Data (dd/mm/yyyy): " + novaDataStr, 
                "Confirmar Alteração", 
                JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION) {
            scoreSelecionado.setScore(novoScore);
            scoreSelecionado.setData(new java.sql.Date(novaData.getTime()));
            
             scoreDAO.atualizar2(scoreSelecionado);
                JOptionPane.showMessageDialog(this, "Score alterado com sucesso!");
                carregarScores();
                toggleCamposEdicao(false);
        }
    }                                                

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {                                                
        dispose();
    }                                               

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonCarregar;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JComboBox<String> jComboBoxScores;
    private javax.swing.JFormattedTextField jFormattedTextFieldNovaData;
    private javax.swing.JLabel jLabelNovaData;
    private javax.swing.JLabel jLabelNovoScore;
    private javax.swing.JLabel jLabelSelecionar;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTextFieldNovoScore;
    // End of variables declaration                   
}