/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Classes.Score;
import Classes.Player;
import Classes.Jogo;
import DAO.ErpDAOException;
import DAO.JogoDAO;
import DAO.ScoreDAO;
import DAO.playerDAO;
import static java.lang.String.format;
import java.sql.Time;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

public class InserirScore extends javax.swing.JFrame {

    private static ArrayList<Player> players = new ArrayList<Player>();
    private static ArrayList<Jogo> jogos = new ArrayList<Jogo>();
    private static ArrayList<Score> scores = new ArrayList<Score>();
    private static int posi, posi2;
    private static int id, id2;

    public InserirScore() {
        initComponents();
        setResizable(false); //sem tela cheia
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        choice1 = new java.awt.Choice();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BT_cancelar = new javax.swing.JButton();
        CB_cliente = new javax.swing.JComboBox();
        CB_veiculo = new javax.swing.JComboBox();
        DC = new datechooser.beans.DateChooserPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        BT_confirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("PLAYER");

        jLabel2.setText("JOGO");

        BT_cancelar.setText("Cancelar");
        BT_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_cancelarActionPerformed(evt);
            }
        });

        CB_cliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CB_cliente.setToolTipText("");
        CB_cliente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CB_clienteItemStateChanged(evt);
            }
        });

        CB_veiculo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CB_veiculo.setToolTipText("");
        CB_veiculo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CB_veiculoItemStateChanged(evt);
            }
        });

        DC.addSelectionChangedListener(new datechooser.events.SelectionChangedListener() {
            public void onSelectionChange(datechooser.events.SelectionChangedEvent evt) {
                DCOnSelectionChange(evt);
            }
        });

        jLabel5.setText("SCORE");

        BT_confirmar.setText("OK");
        BT_confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_confirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(60, 60, 60))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CB_veiculo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CB_cliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DC, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel5)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BT_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BT_confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(121, 121, 121))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CB_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CB_veiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(DC, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BT_confirmar, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(BT_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_cancelarActionPerformed
        dispose();
    }//GEN-LAST:event_BT_cancelarActionPerformed

    private void CB_clienteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CB_clienteItemStateChanged
         posi = CB_cliente.getSelectedIndex(); 
    if (posi >= 0 && posi < players.size()) { 
        id = players.get(posi).getId_player(); 
    }
    }//GEN-LAST:event_CB_clienteItemStateChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        carregaComboJogos();
        carregaComboPlayers();
    }//GEN-LAST:event_formWindowOpened

    private void CB_veiculoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CB_veiculoItemStateChanged
        posi2 = (int) CB_veiculo.getSelectedIndex();
        id2 = jogos.get(posi2).getId_game();
    }//GEN-LAST:event_CB_veiculoItemStateChanged

    private void DCOnSelectionChange(datechooser.events.SelectionChangedEvent evt) {//GEN-FIRST:event_DCOnSelectionChange

    }//GEN-LAST:event_DCOnSelectionChange

    private void BT_confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_confirmarActionPerformed
    ScoreDAO pdao = new ScoreDAO();
    Score A = new Score();
    A.setId_game(id2);
    A.setId_player(id);
    Calendar dateStart = DC.getSelectedDate();
    if (dateStart == null) {
        JOptionPane.showMessageDialog(this, "Por favor selecione a data");
        return;
    }
    Date data = dateStart.getTime();
    A.setData(data);
    try {
        int valorTotal = Integer.parseInt(jTextField1.getText());
        A.setScore(valorTotal);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Insira um valor válido para o score.");
        return;
    }
    try {
        pdao.inserir(A);
        JOptionPane.showMessageDialog(this, "Score registrado com sucesso!");
        dispose();
    } catch (ErpDAOException ex) {
        Logger.getLogger(InserirScore.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "Erro ao registrar Score.");
    }

    }//GEN-LAST:event_BT_confirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void carregaComboJogos() {
        CB_veiculo.removeAllItems();
        JogoDAO vDAO = new JogoDAO();
       jogos = vDAO.listar();
        for (int i = 0; i < jogos.size(); i++) {
            CB_veiculo.addItem(jogos.get(i).getNome());

        }
    }

    public static void carregaComboPlayers() {
        CB_cliente.removeAllItems();
        playerDAO cDAO = new playerDAO();
        players = cDAO.listar();

        for (int i = 0; i < players.size(); i++) {
            CB_cliente.addItem(players.get(i).getNickname());

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_cancelar;
    private javax.swing.JButton BT_confirmar;
    private static javax.swing.JComboBox CB_cliente;
    private static javax.swing.JComboBox CB_veiculo;
    private datechooser.beans.DateChooserPanel DC;
    private java.awt.Choice choice1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
 private JTextArea setString(String date) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
